import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Iluminação - Parobé",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css"></link>
        <link rel="stylesheet" href="https://unpkg.com/leaflet/dist/leaflet.css" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <script src="https://unpkg.com/leaflet/dist/leaflet.js"></script>
        {children}
        <footer className="bg-blue-400 py-5 px-10 text-white text-xs space-y-1 text-left">
          <h2><i className="mr-3 bi bi-building-fill"></i>Prefeitura Municipal de Parobé</h2>
          <h2><i className="mr-3 bi bi-lightbulb-fill"></i>Secretaria de Obras</h2>
          <h2><i className="mr-3 bi bi-pc-display"></i>Desenvolvido pelo Departamento de TI</h2>
        </footer>
      </body>
    </html>
  );
}
